version: '3.8'

services:
  strapi:
    build: .
    container_name: strapi_app
    env_file: .env
    ports:
      - "1337:1337"
    volumes:
      - ./public/uploads:/opt/app/public/uploads
    restart: unless-stopped
    networks:
      - strapi-net

networks:
  strapi-net:
    driver: bridge
