version: '3.8'

services:
  strapi:
    container_name: strapi_app
    build: .
    image: my-strapi-app # Đặt tên image của bạn
    restart: unless-stopped
    env_file: .env # Nạp biến môi trường từ file .env
    ports:
      - "1337:1337"
    volumes:
      # Mount thư mục uploads để dữ liệu không bị mất khi container khởi động lại
      - ./public/uploads:/opt/app/public/uploads
    networks:
      - strapi-net

networks:
  strapi-net:
    driver: bridge